// flow-typed signature: b2b3565dfefb0e53f84b2f85deb52ae6
// flow-typed version: <<STUB>>/axios-digest_v^0.1.1/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'axios-digest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'axios-digest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'axios-digest/index' {
  declare module.exports: $Exports<'axios-digest'>;
}
declare module 'axios-digest/index.js' {
  declare module.exports: $Exports<'axios-digest'>;
}
