// flow-typed signature: 35a41257a3e29e8c1967ef4aedbc90a8
// flow-typed version: <<STUB>>/digest-auth-request_v^0.7.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'digest-auth-request'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'digest-auth-request' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'digest-auth-request/digestAuthRequest' {
  declare module.exports: any;
}

// Filename aliases
declare module 'digest-auth-request/digestAuthRequest.js' {
  declare module.exports: $Exports<'digest-auth-request/digestAuthRequest'>;
}
