// flow-typed signature: cbe0d98406770ec40936b71a441a17cb
// flow-typed version: <<STUB>>/material-table_v^1.40.1/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'material-table'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'material-table' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'material-table/dist/components/index' {
  declare module.exports: any;
}

declare module 'material-table/dist/components/m-table-action' {
  declare module.exports: any;
}

declare module 'material-table/dist/components/m-table-actions' {
  declare module.exports: any;
}

declare module 'material-table/dist/components/m-table-body-row' {
  declare module.exports: any;
}

declare module 'material-table/dist/components/m-table-body' {
  declare module.exports: any;
}

declare module 'material-table/dist/components/m-table-cell' {
  declare module.exports: any;
}

declare module 'material-table/dist/components/m-table-edit-field' {
  declare module.exports: any;
}

declare module 'material-table/dist/components/m-table-edit-row' {
  declare module.exports: any;
}

declare module 'material-table/dist/components/m-table-filter-row' {
  declare module.exports: any;
}

declare module 'material-table/dist/components/m-table-group-row' {
  declare module.exports: any;
}

declare module 'material-table/dist/components/m-table-groupbar' {
  declare module.exports: any;
}

declare module 'material-table/dist/components/m-table-header' {
  declare module.exports: any;
}

declare module 'material-table/dist/components/m-table-pagination' {
  declare module.exports: any;
}

declare module 'material-table/dist/components/m-table-stepped-pagination' {
  declare module.exports: any;
}

declare module 'material-table/dist/components/m-table-toolbar' {
  declare module.exports: any;
}

declare module 'material-table/dist/default-props' {
  declare module.exports: any;
}

declare module 'material-table/dist/index' {
  declare module.exports: any;
}

declare module 'material-table/dist/material-table' {
  declare module.exports: any;
}

declare module 'material-table/dist/prop-types' {
  declare module.exports: any;
}

declare module 'material-table/dist/utils/data-manager' {
  declare module.exports: any;
}

declare module 'material-table/dist/utils/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'material-table/dist/components/index.js' {
  declare module.exports: $Exports<'material-table/dist/components/index'>;
}
declare module 'material-table/dist/components/m-table-action.js' {
  declare module.exports: $Exports<'material-table/dist/components/m-table-action'>;
}
declare module 'material-table/dist/components/m-table-actions.js' {
  declare module.exports: $Exports<'material-table/dist/components/m-table-actions'>;
}
declare module 'material-table/dist/components/m-table-body-row.js' {
  declare module.exports: $Exports<'material-table/dist/components/m-table-body-row'>;
}
declare module 'material-table/dist/components/m-table-body.js' {
  declare module.exports: $Exports<'material-table/dist/components/m-table-body'>;
}
declare module 'material-table/dist/components/m-table-cell.js' {
  declare module.exports: $Exports<'material-table/dist/components/m-table-cell'>;
}
declare module 'material-table/dist/components/m-table-edit-field.js' {
  declare module.exports: $Exports<'material-table/dist/components/m-table-edit-field'>;
}
declare module 'material-table/dist/components/m-table-edit-row.js' {
  declare module.exports: $Exports<'material-table/dist/components/m-table-edit-row'>;
}
declare module 'material-table/dist/components/m-table-filter-row.js' {
  declare module.exports: $Exports<'material-table/dist/components/m-table-filter-row'>;
}
declare module 'material-table/dist/components/m-table-group-row.js' {
  declare module.exports: $Exports<'material-table/dist/components/m-table-group-row'>;
}
declare module 'material-table/dist/components/m-table-groupbar.js' {
  declare module.exports: $Exports<'material-table/dist/components/m-table-groupbar'>;
}
declare module 'material-table/dist/components/m-table-header.js' {
  declare module.exports: $Exports<'material-table/dist/components/m-table-header'>;
}
declare module 'material-table/dist/components/m-table-pagination.js' {
  declare module.exports: $Exports<'material-table/dist/components/m-table-pagination'>;
}
declare module 'material-table/dist/components/m-table-stepped-pagination.js' {
  declare module.exports: $Exports<'material-table/dist/components/m-table-stepped-pagination'>;
}
declare module 'material-table/dist/components/m-table-toolbar.js' {
  declare module.exports: $Exports<'material-table/dist/components/m-table-toolbar'>;
}
declare module 'material-table/dist/default-props.js' {
  declare module.exports: $Exports<'material-table/dist/default-props'>;
}
declare module 'material-table/dist/index.js' {
  declare module.exports: $Exports<'material-table/dist/index'>;
}
declare module 'material-table/dist/material-table.js' {
  declare module.exports: $Exports<'material-table/dist/material-table'>;
}
declare module 'material-table/dist/prop-types.js' {
  declare module.exports: $Exports<'material-table/dist/prop-types'>;
}
declare module 'material-table/dist/utils/data-manager.js' {
  declare module.exports: $Exports<'material-table/dist/utils/data-manager'>;
}
declare module 'material-table/dist/utils/index.js' {
  declare module.exports: $Exports<'material-table/dist/utils/index'>;
}
