// flow-typed signature: 49057ec04e5e8fe457b8472dfa092055
// flow-typed version: <<STUB>>/react-material-ui-datatable_v^2.0.0-alpha.29/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-material-ui-datatable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-material-ui-datatable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-material-ui-datatable/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-material-ui-datatable/dist/index.js' {
  declare module.exports: $Exports<'react-material-ui-datatable/dist/index'>;
}
