// flow-typed signature: 0fc7c90195c401d6fbc139dbc006beb1
// flow-typed version: <<STUB>>/request-digest_v^1.0.13/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'request-digest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'request-digest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'request-digest/request-digest.es5' {
  declare module.exports: any;
}

declare module 'request-digest/request-digest.es6' {
  declare module.exports: any;
}

declare module 'request-digest/request-digest' {
  declare module.exports: any;
}

// Filename aliases
declare module 'request-digest/request-digest.es5.js' {
  declare module.exports: $Exports<'request-digest/request-digest.es5'>;
}
declare module 'request-digest/request-digest.es6.js' {
  declare module.exports: $Exports<'request-digest/request-digest.es6'>;
}
declare module 'request-digest/request-digest.js' {
  declare module.exports: $Exports<'request-digest/request-digest'>;
}
